const texts = [
  'black holes are invisible but astronomers can observe them indirectly by the way they affect their surroundings for example black holes can be surrounded by rings of gas and dust called accretion disks that emit light across many wavelengths including x rays as gas flows around a black hole, it heats up making these invisible objects into some of the brightest things in the entire universe',
  'on a bright summer day the bustling city streets were filled with people hurrying to their destinations cars honked and buses rumbled by as street vendors sold their colorful wares the smell of fresh baked bread wafted from a nearby bakery mixing with the scent of blooming flowers in the park where children laughed and played in the warm sunshine',
  'in the quiet village nestled among rolling hills the old stone houses stood in a row with colorful flowers spilling from their windowsills the church bells chimed in the distance as villagers went about their day chatting and laughing under the bright sun',
  'deep in the mysterious jungle exotic birds sang their melodic songs monkeys swung from tree to tree with playful abandon and colorful butterflies danced among the lush foliage a gentle stream meandered through the dense undergrowth creating soothing whispers in the air',
  'high atop the snowy mountain peaks the air was crisp and pure as skiers glided down the slopes with exhilarating speed below in the cozy lodge a fire crackled in the hearth as visitors warmed themselves with hot cocoa and shared tales of their adventures',
  'in the vast desert sands stretched endlessly under the blazing sun mirages shimmered on the horizon as camels plodded steadily across the dunes nomads in colorful robes rode alongside their loyal companions seeking refuge in oasis hidden among the golden waves',
  'beneath the sparkling ocean waves a world of wonder awaited schools of fish darted in intricate patterns among swaying coral reefs while majestic sea turtles glided gracefully through the azure waters above dolphins leaped in joyful arcs as the rays filtered down illuminating this hidden paradise',
];

export default texts[Math.floor(Math.random() * texts.length)];
